run:
  timeout: 5m
  tests: true
  concurrency: 1

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - typecheck
    - revive
    - gofmt
    - goimports
    - gosimple
    - nakedret
    - exportloopref
    - gocritic
    - misspell
    - rowserrcheck
    - whitespace

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - log.Printf
      - log.Println

  goimports:
    local-prefixes: github.com/platform9/pf9-oidc-proxy

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - dupImport
      - rangeValCopy

  revive:
    severity: warning
    rules:
      - name: indent-error-flow
      - name: var-naming
      - name: imports-blacklist
        arguments:
          - fmt
      - name: error-naming
      - name: time-naming

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude-dirs:
    - vendor
    - test/e2e
    - bin
    - mocks
    - generated
  exclude-files:
    - ".*_generated.go"
    - ".*mock_.*.go"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

output:
  formats:
    - format: colored-line-number
  sort-results: true
