name: CI

on:
  push:
    branches: [ private/pf9-oidc/harsh/unit-test ]
  pull_request:
    branches: [ private/pf9-oidc/harsh/unit-test ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: make depend

    - name: Install go-junit-report
      run: go install github.com/jstemmer/go-junit-report@latest

    - name: Add Go bin to PATH
      run: echo "${HOME}/go/bin" >> $GITHUB_PATH

    - name: Run golangci-lint
      run: make go_lint

    - name: Run unit tests
      run: make test

    - name: Run e2e tests
      run: make e2e
