name: Lint

on:
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  push:
    branches:
      - pf9-oidc

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run golangci-lint
        run: make lint
